# Site settings
title: Personal Website
description: Technology has improved and this is a new era. We have systems control home appliances over voice, smartphones and remotes. Here I propose an automated home automation that works on speech processing.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Islam Kamilov
user_description: Motivated to build software program and experienced working with groups. Dedicated to learning and improving programs. Background in software development and cyber security.
user_title: Software Engineer | Cyber Security Engineer
email: kamilov6@gmail.com
twitter_username: IslamKamilov
github_username:  ikamilov
gplus_username:  u/0/106863272901917873979

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
